name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: cmake
      run: cmake . &> cmake.log 
        
    - name: upload cmake log  
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cmake log
        path: cmake.log
        
    - name: make
      run: make -j8 &> make.log

    - name: upload make log
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: make log
        path: make.log
          
    - name: run tests
      run: ./t_version &> tests.log
    
    - name: upload tests execution log
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: tests execution log
        path: tests.log
        
    - name: Upload binaries.
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: static library
        path: libtcl.a
