name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: System info
      run: lscpu
    - name: Build all
      run: | 
        cmake . > cmake.log
        make -j8 > make.log
    - name: Run
      run: ./t_version execution.log
