name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: System info
      run: lscpu
    - name: Build all
      run: | 
        cmake . > cmake.log
        make -j8 > make.log
        
    - uses: actions/upload-artifact@v1
      with:
        name: cmake log
        path: cmake.log

    - uses: actions/upload-artifact@v1
      with:
        name: make log
        path: make.log
          
    - name: Run
      run: ./t_version > execution.log

    - uses: actions/upload-artifact@v1
      with:
        name: execution log
        path: execution.log
