name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: System info
      run: lscpu
    - name: Build all
      run: | 
        cmake . &> cmake.log
        make -j8 &> make.log
        
    - name: Upload CMake log.  
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: CMake log.
        path: cmake.log

    - name: Upload make log.
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: make log.
        path: make.log
          
    - name: Run
      run: ./t_version &> execution.log
    
    - name: Upload execution log.
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: Execution log.
        path: execution.log
        
    - name: Upload binaries.
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: Static library.
        path: libtcl.a
