name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: cmake
      run: cmake CMakeLists.txt -B"build" &> cmake.log 
        
    - name: upload cmake log  
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cmake log
        path: cmake.log
        
    - name: make
      run: cd build && make -j8 &> make.log

    - name: upload make log
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: make log
        path: make.log
          
    - name: run tests
      run: cd build/test && ./tests &> tests.log
    
    - name: upload tests execution log
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: tests execution log
        path: build/test/tests.log
