name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: build all
      run:  chmod +x scripts/build_all.sh && scripts/build_all.sh
        
    - name: upload build logs 
      uses: actions/upload-artifact@v1
      # if: failure()
      with:
        name: build logs
        path: logs
        

