name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    # Style check can be turned on, but it failed for now, because there is no suitable config. 
      
    # - name: style check
    #  uses: DoozyX/clang-format-lint-action@v0.5
    #  with:
    #    source: '.'
    #    extensions: 'h,cpp,c'
    #    clangFormatVersion: 9
    #    style: llvm
      
    - name: build all
      run:  chmod +x scripts/build_all.sh && scripts/build_all.sh
        
    - name: upload build logs
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: TCL build logs [commit sha - ${{ github.sha }}]
        path: logs

    - name: run algorithmic tests
      run:  chmod +x scripts/run_alg_tests.sh && scripts/run_alg_tests.sh
        
    - name: upload tests logs 
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: TCL build and test logs [commit sha - ${{ github.sha }}]
        path: logs
      
    - name: collect binaries 
      run:  chmod +x scripts/collect_binaries.sh && scripts/collect_binaries.sh
           
    - name: upload binaries 
      uses: actions/upload-artifact@v1
      if: success()
      with:
        name: TCL binaries [commit sha - ${{ github.sha }}]
        path: binaries
