name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: build all
      run:  chmod +x scripts/build_all.sh && scripts/build_all.sh
        
    - name: upload build logs 
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: $GITHUB_SHA build logs
        path: logs

    - name: run algorithmic tests
      run:  chmod +x scripts/run_alg_tests.sh && scripts/run_alg_tests.sh
        
    - name: upload tests logs 
      uses: actions/upload-artifact@v1
      # if: failure()
      with:
        name: $GITHUB_SHA build and test logs logs
        path: logs
        

