name: CI-CD

on:
  pull_request:
    branches: [ master ]

jobs:
    CI:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2

      # Style check can be turned on, but it failed for now, because there is no suitable config. 

      # - name: style check
      #  uses: DoozyX/clang-format-lint-action@v0.5
      #  with:
      #    source: '.'
      #    extensions: 'h,cpp,c'
      #    clangFormatVersion: 9
      #    style: llvm

      - name: Build
        run:  chmod +x scripts/build_all.sh && scripts/build_all.sh

      - name: Upload build logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: TCL build logs [commit sha - ${{ github.sha }}]
          path: logs
      
      - name: Run tests
        run:  chmod +x scripts/run_alg_tests.sh && run_alg_tests.sh
      
      - name: Upload testing logs
        uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: TCL testing logs [commit sha - ${{ github.sha }}]
          path: logs/alg_tests.log
        
      - name: Collect binaries 
        run:  chmod +x scripts/collect_binaries.sh && scripts/collect_binaries.sh

      - name: Upload binaries 
        uses: actions/upload-artifact@v1
        if: success()
        with:
          name: TCL binaries [commit sha - ${{ github.sha }}]
          path: binaries

    CD:
      needs: CI
      runs-on: ubuntu-latest
      
      steps:
        - name: Download TCL binaries
          uses: actions/download-artifact@v1
          with:
            name: TCL binaries [commit sha - ${{ github.sha }}]
            
        - name: Run performance tests
          run: cd "TCL binaries [commit sha - ${{ github.sha }}]" && chmod +x perfs && ./perfs &> perf_tests.log
          
        - name: Upload performance testing logs
          uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: TCL performance testing logs [commit sha - ${{ github.sha }}]
            path: "TCL binaries [commit sha - ${{ github.sha }}]/perf_tests.log"
